CRAN <- "https://cloud.r-project.org"
# install.packages('shiny', repos = CRAN)
# install.packages('rsconnect', repos = CRAN)
# install.packages('palmerpenguins', repos = CRAN)
# install.packages('dplyr', repos = CRAN)
# install.packages('ggplot2', repos = CRAN)
# install.packages('macleish', repos = CRAN)
# install.packages('plotly', repos = CRAN)
# install.packages('lubridate', repos = CRAN)
install.packages('sf', repos = CRAN)